# Generated by Django 4.2.10 on 2024-03-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tf_correct_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
