# Generated by Django 4.2.10 on 2024-03-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_question_tf_correct_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("mc", "Multiple Choice"), ("tf", "True/False")],
                default="tf",
                max_length=2,
            ),
        ),
    ]
